/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWorkforceRouteImport } from './routes/app.workforce'
import { Route as AppTasksRouteImport } from './routes/app.tasks'
import { Route as AppSettlementsRouteImport } from './routes/app.settlements'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppProjectsRouteImport } from './routes/app.projects'
import { Route as AppPostureRouteImport } from './routes/app.posture'
import { Route as AppIdentityRouteImport } from './routes/app.identity'
import { Route as AppGovernanceRouteImport } from './routes/app.governance'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppComplianceRouteImport } from './routes/app.compliance'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppProjectsIdRouteImport } from './routes/app.projects.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkforceRoute = AppWorkforceRouteImport.update({
  id: '/workforce',
  path: '/workforce',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSettlementsRoute = AppSettlementsRouteImport.update({
  id: '/settlements',
  path: '/settlements',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppPostureRoute = AppPostureRouteImport.update({
  id: '/posture',
  path: '/posture',
  getParentRoute: () => AppRoute,
} as any)
const AppIdentityRoute = AppIdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => AppRoute,
} as any)
const AppGovernanceRoute = AppGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceRoute = AppComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/audit': typeof AppAuditRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/governance': typeof AppGovernanceRoute
  '/app/identity': typeof AppIdentityRoute
  '/app/posture': typeof AppPostureRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/settlements': typeof AppSettlementsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/workforce': typeof AppWorkforceRoute
  '/app/': typeof AppIndexRoute
  '/app/projects/$id': typeof AppProjectsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/audit': typeof AppAuditRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/governance': typeof AppGovernanceRoute
  '/app/identity': typeof AppIdentityRoute
  '/app/posture': typeof AppPostureRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/settlements': typeof AppSettlementsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/workforce': typeof AppWorkforceRoute
  '/app': typeof AppIndexRoute
  '/app/projects/$id': typeof AppProjectsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/audit': typeof AppAuditRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/governance': typeof AppGovernanceRoute
  '/app/identity': typeof AppIdentityRoute
  '/app/posture': typeof AppPostureRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/settlements': typeof AppSettlementsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/workforce': typeof AppWorkforceRoute
  '/app/': typeof AppIndexRoute
  '/app/projects/$id': typeof AppProjectsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/audit'
    | '/app/compliance'
    | '/app/dashboard'
    | '/app/governance'
    | '/app/identity'
    | '/app/posture'
    | '/app/projects'
    | '/app/reports'
    | '/app/settlements'
    | '/app/tasks'
    | '/app/workforce'
    | '/app/'
    | '/app/projects/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/audit'
    | '/app/compliance'
    | '/app/dashboard'
    | '/app/governance'
    | '/app/identity'
    | '/app/posture'
    | '/app/projects'
    | '/app/reports'
    | '/app/settlements'
    | '/app/tasks'
    | '/app/workforce'
    | '/app'
    | '/app/projects/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/audit'
    | '/app/compliance'
    | '/app/dashboard'
    | '/app/governance'
    | '/app/identity'
    | '/app/posture'
    | '/app/projects'
    | '/app/reports'
    | '/app/settlements'
    | '/app/tasks'
    | '/app/workforce'
    | '/app/'
    | '/app/projects/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workforce': {
      id: '/app/workforce'
      path: '/workforce'
      fullPath: '/app/workforce'
      preLoaderRoute: typeof AppWorkforceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settlements': {
      id: '/app/settlements'
      path: '/settlements'
      fullPath: '/app/settlements'
      preLoaderRoute: typeof AppSettlementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/posture': {
      id: '/app/posture'
      path: '/posture'
      fullPath: '/app/posture'
      preLoaderRoute: typeof AppPostureRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/identity': {
      id: '/app/identity'
      path: '/identity'
      fullPath: '/app/identity'
      preLoaderRoute: typeof AppIdentityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/governance': {
      id: '/app/governance'
      path: '/governance'
      fullPath: '/app/governance'
      preLoaderRoute: typeof AppGovernanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compliance': {
      id: '/app/compliance'
      path: '/compliance'
      fullPath: '/app/compliance'
      preLoaderRoute: typeof AppComplianceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/$id': {
      id: '/app/projects/$id'
      path: '/$id'
      fullPath: '/app/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
  }
}

interface AppProjectsRouteChildren {
  AppProjectsIdRoute: typeof AppProjectsIdRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsIdRoute: AppProjectsIdRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppComplianceRoute: typeof AppComplianceRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGovernanceRoute: typeof AppGovernanceRoute
  AppIdentityRoute: typeof AppIdentityRoute
  AppPostureRoute: typeof AppPostureRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppReportsRoute: typeof AppReportsRoute
  AppSettlementsRoute: typeof AppSettlementsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppWorkforceRoute: typeof AppWorkforceRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppComplianceRoute: AppComplianceRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGovernanceRoute: AppGovernanceRoute,
  AppIdentityRoute: AppIdentityRoute,
  AppPostureRoute: AppPostureRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppReportsRoute: AppReportsRoute,
  AppSettlementsRoute: AppSettlementsRoute,
  AppTasksRoute: AppTasksRoute,
  AppWorkforceRoute: AppWorkforceRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
